on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  build:
    permissions:
      repository-projects: write
      contents: write
    name: build
    strategy:
      matrix:
        platform: [ubuntu-latest]
        # platform: [macos-latest,ubuntu-latest,mac-arm,windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: rust-toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            # https://github.com/dalek-cryptography/curve25519-dalek/issues/618
            toolchain: nightly
            cache: false
            # toolchain: nightly-2024-05-04
            components: rust-src
            # components: rustfmt, clippy

      - name: checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: false
          lfs: true
          path: src

      - name: checkout dist conf
        uses: actions/checkout@v4
        with:
          repository: i18n-dist/dist
          token: ${{ secrets.GH_PAT }}
          path: dist

      - name: github release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./src/sh/github.release.sh

      - name: 部署到线上服务器
        shell: bash
        run: |
          ./src/sh/deploy.sh $(pwd)/dist
