name: api

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  build:
    permissions:
      repository-projects: write
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      name: ipv6_proxy
    secrets: inherit
